# -*- coding: utf-8 -*-
"""eda_and_kpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOPQBoPaDt-dvBcq5J7Ey5DIf4yhsbOP

# E-Commerce KPI Analysis 2023
**Author:** Nasim Maleki | Business Analyst  
**Dataset:** European e-commerce · 5,260 orders ·   
**Goal:** Identify root cause of Q3 revenue drop and define key performance indicators
"""

# import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Data Structure**"""

# read data from GitHub
BASE = "https://raw.githubusercontent.com/nasimmaaleki/ecommerce-kpi-analysis/main/data/"

orders = pd.read_csv(BASE + "orders.csv")
customers = pd.read_csv(BASE + "customers.csv")
products = pd.read_csv(BASE + "products.csv")
order_items = pd.read_csv(BASE + "order_items.csv")

print("orders:", orders.shape)
print("customers:", customers.shape)
print("products:", products.shape)
print("order_items:", order_items.shape)

print(orders.columns)
print(customers.columns)
print(products.columns)
print(order_items.columns)

print(orders.shape)
print(orders.dtypes)
print(orders.head())
print(orders.isnull().sum())
print (customers.shape)
print(customers.dtypes)
print(customers.head())
print(customers.isnull().sum())
print (products.shape)
print(products.dtypes)
print(products.head())
print(products.isnull().sum())
print (order_items.shape)
print(order_items.dtypes)
print(order_items.head())
print(order_items.isnull().sum())

"""**Fixing data**"""

orders["order_date"]= pd.to_datetime(orders["order_date"])
orders["order_month"]= orders["order_date"].dt.to_period("M")
customers['join_date']= pd.to_datetime(customers['join_date'])
customers['join_month']= customers['join_date'].dt.to_period("M")

"""**Define KPIs**"""

orders['status'].unique()

# order's table KPIs
# Total revenue (completed orders only)
completed= orders[orders["status"] == "Completed"]
total_revenue= completed["order_total"].sum()
# Average order value
aov= completed["order_total"].mean()

# Return rate
return_rate= len(orders[orders["status"] == "Returned"]) / len(orders) * 100

print(f"Total Revenue: €{total_revenue:,.0f}")
print(f"Average Order Value: €{aov:.2f}")
print(f"Return Rate: {return_rate:.2f}%")

"""Revenue KPIs"""

# Quarterly revenue
quarterly_revenue = completed.groupby("quarter")["order_total"].sum()

# Monthly revenue
monthly_revenue = completed.groupby("order_month")["order_total"].sum()

# Quarter-over-quarter growth rate
qoq_growth = quarterly_revenue.pct_change() * 100

"""Customer Loyalty"""

# Average Number of orders

orders_per_customer= completed.groupby("customer_id")["order_id"].count()
avg_orders = orders_per_customer.mean()
print(f"Average orders per customer: {avg_orders:.2f}")

# Lifecycle
reference_date = pd.Timestamp("2023-12-31")
customers["lifecycle_months"] = (
    reference_date - customers["join_date"]
).dt.days / 30

# Count completed orders per customer
completed_counts= completed.groupby("customer_id")["order_id"].count().reset_index()
completed_counts.columns= ["customer_id", "order_count"]
customer_summary= customers[["customer_id", "lifecycle_months"]].merge(
    completed_counts,
    on="customer_id",
    how="left")

# Fill NaN with 0 (customers who joined but never completed an order)
customer_summary["order_count"] = customer_summary["order_count"].fillna(0)

# Your loyalty definition
customer_summary["is_loyal"] = (
    (customer_summary["order_count"] > avg_orders) &
    (customer_summary["lifecycle_months"] >= 6))

"""Channel Performance:

Which channel brings the most completed orders?

Which channel generates the most revenue?
"""

channel_orders = completed.groupby("channel")["order_id"].count()
channel_revenue = completed.groupby("channel")["order_total"].sum()
channel_summary = pd.DataFrame({
    "orders": channel_orders,
    "revenue": channel_revenue
})
channel_summary["avg_order_value"] = channel_summary["revenue"] / channel_summary["orders"]

"""Product & Category Performance"""

completed_items = order_items.merge(completed[["order_id"]],on="order_id", how="inner")

# Orders per category
orders_per_category = completed_items.groupby("category")["order_id"].nunique()
# Revenue per category
revenue_per_category = completed_items.groupby("category")["line_total"].sum()
# Orders per product
orders_per_product = completed_items.groupby("product_id")["order_id"].nunique()

"""Most Valuable Products"""

product_performance = completed_items.merge(
    products.drop(columns=["category", "unit_price"]),
    on="product_id",
    how="left"
)

product_kpi = product_performance.groupby(["product_id", "product_name", "category"]).agg(total_orders = ("order_id", "nunique"),
    total_revenue= ("line_total", "sum"),
    units_sold = ("quantity", "sum")
).reset_index()

# most valuable products
top_products = product_kpi.sort_values("total_revenue", ascending=False).head(10)

"""Most Valuable Customers"""

customer_kpi = completed.groupby("customer_id").agg(
    total_orders= ("order_id", "count"),
    total_spent= ("order_total", "sum"),
    avg_order_value= ("order_total", "mean")
).reset_index()

top_customers= customer_kpi.sort_values("total_spent", ascending=False).head(10)

# Join with customer info to see segment and country
top_customers = top_customers.merge(
    customers[["customer_id", "segment", "country", "acquisition_channel"]],
    on="customer_id"
)

#SUMMARY OUTPUT
# Revenue KPIs
print("=== REVENUE KPIs ===")
print(f"Total Revenue        : €{total_revenue:,.0f}")
print(f"Average Order Value  : €{aov:.2f}")
print(f"Return Rate          : {return_rate:.2f}%")

# Quarterly trend
print("\n=== QUARTERLY REVENUE ===")
print(quarterly_revenue.to_string())

print("\n=== QUARTER-OVER-QUARTER GROWTH % ===")
print(qoq_growth.to_string())

print("\n=== MONTHLY REVENUE ===")
print(monthly_revenue.to_string())

# Customer loyalty
loyal_count = customer_summary["is_loyal"].sum()
loyalty_rate = loyal_count / len(customer_summary) * 100

print("\n=== CUSTOMER LOYALTY ===")
print(f"Average orders per customer : {avg_orders:.2f}")
print(f"Loyal customers             : {loyal_count}")
print(f"Loyalty rate                : {loyalty_rate:.1f}%")

# Channel performance
print("\n=== CHANNEL PERFORMANCE ===")
print(channel_summary.sort_values("revenue", ascending=False).to_string())

# Category performance
print("\n=== REVENUE PER CATEGORY ===")
print(revenue_per_category.sort_values(ascending=False).to_string())

print("\n=== ORDERS PER CATEGORY ===")
print(orders_per_category.sort_values(ascending=False).to_string())

# Product performance
print("\n=== TOP 10 MOST VALUABLE PRODUCTS ===")
print(top_products[["product_name", "category", "total_orders", "units_sold", "total_revenue"]].to_string(index=False))

# Customer performance
print("\n=== TOP 10 MOST VALUABLE CUSTOMERS ===")
print(top_customers[["customer_id", "segment", "country", "total_orders", "total_spent"]].to_string(index=False))

"""**EDA phase**"""

# Visual style
plt.rcParams.update({
    "figure.facecolor":  "#0f1117",
    "axes.facecolor":    "#1a1d27",
    "axes.edgecolor":    "#2e3350",
    "axes.labelcolor":   "#e8eaf0",
    "xtick.color":       "#7b82a0",
    "ytick.color":       "#7b82a0",
    "text.color":        "#e8eaf0",
    "grid.color":        "#2e3350",
    "grid.linestyle":    "--",
    "grid.alpha":        0.5,
    "figure.figsize":    (12, 5),
    "font.family":       "DejaVu Sans",
})

"""Chart 1: Monthly Revenue Trend"""

import os
os.makedirs("analysis", exist_ok=True)

fig, ax = plt.subplots()

colors_map = {
    "2023-01": "#6366f1", "2023-02": "#6366f1", "2023-03": "#6366f1",
    "2023-04": "#14b8a6", "2023-05": "#14b8a6", "2023-06": "#14b8a6",
    "2023-07": "#ef4444", "2023-08": "#ef4444", "2023-09": "#ef4444",
    "2023-10": "#22c55e", "2023-11": "#22c55e", "2023-12": "#22c55e",
}

ax.bar(
    monthly_revenue.index,
    monthly_revenue.values,
    color=[colors_map[m] for m in monthly_revenue.index],
    width=0.6,
    zorder=2
)
for i, (month, value) in enumerate(monthly_revenue.items()):
    ax.text(i, value + 3000, f"€{value/1000:.0f}K",
            ha="center", va="bottom", fontsize=8, color="#7b82a0")

# Q3 annotation
ax.annotate(
    "Q3 dip: −27.6%",
    xy=(6, monthly_revenue.iloc[6]),
    xytext=(6, monthly_revenue.iloc[6] + 35000),
    ha="center", color="#ef4444", fontsize=9,
    arrowprops=dict(arrowstyle="->", color="#ef4444")
)

ax.set_title("Monthly Revenue 2023", fontsize=14, pad=15)
ax.set_xlabel("Month", labelpad=10)
ax.set_ylabel("Revenue (€)", labelpad=10)
ax.set_xticks(range(len(monthly_revenue.index)))
ax.set_xticklabels(monthly_revenue.index, rotation=45, ha="right")
ax.yaxis.set_major_formatter(
    plt.FuncFormatter(lambda x, _: f"€{x/1000:.0f}K")
)

from matplotlib.patches import Patch
legend = [
    Patch(color="#6366f1", label="Q1"),
    Patch(color="#14b8a6", label="Q2"),
    Patch(color="#ef4444", label="Q3"),
    Patch(color="#22c55e", label="Q4"),
]
ax.legend(handles=legend, loc="upper left", framealpha=0.2)

plt.tight_layout()
plt.savefig("analysis/chart_monthly_revenue.png", dpi=150, bbox_inches="tight")
plt.show()

"""Chart 2: Quarterly Revenue Bar Chart"""

plt.figure()
colors = ["steelblue", "steelblue", "crimson", "steelblue"]
quarterly_revenue.plot(kind="bar", color=colors)
plt.title("Quarterly Revenue 2023 — Q3 Dip Highlighted")
plt.xlabel("Quarter")
plt.ylabel("Revenue (€)")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("analysis/chart_quarterly_revenue.png")
plt.show()

"""Chart 3 — Revenue by Category"""

plt.figure()
revenue_per_category.sort_values().plot(kind="barh", color="steelblue")
plt.title("Revenue by Product Category")
plt.xlabel("Revenue (€)")
plt.tight_layout()
plt.savefig("analysis/chart_category_revenue.png")
plt.show()

"""Chart 4: Channel Performance (orders vs revenue)"""

fig, axes = plt.subplots(1, 2)

channel_summary["orders"].sort_values().plot(kind="barh", ax=axes[0], color="steelblue")
axes[0].set_title("Orders by Channel")

channel_summary["revenue"].sort_values().plot(kind="barh", ax=axes[1], color="teal")
axes[1].set_title("Revenue by Channel")

plt.tight_layout()
plt.savefig("analysis/chart_channel_performance.png")
plt.show()

"""Chart 5: Top 10 Products"""

plt.figure()
top_products.set_index("product_name")["total_revenue"].sort_values().plot(
    kind="barh", color="steelblue"
)
plt.title("Top 10 Products by Revenue")
plt.xlabel("Revenue (€)")
plt.tight_layout()
plt.savefig("analysis/chart_top_products.png")
plt.show()

"""Chart 6: Loyal vs Non-Loyal Customers (pie)"""

plt.figure(figsize=(6, 6))
labels = ["Loyal", "Not Loyal"]
sizes  = [loyal_count, len(customer_summary) - loyal_count]
colors = ["steelblue", "lightgray"]
plt.pie(sizes, labels=labels, colors=colors, autopct="%1.1f%%", startangle=90)
plt.title("Customer Loyalty Distribution")
plt.tight_layout()
plt.savefig("analysis/chart_loyalty.png")
plt.show()

"""# Does discount level correlate with order value?"""

discount_corr = order_items[["discount", "line_total"]].corr()
print(discount_corr)

fig, ax = plt.subplots()
ax.scatter(
    order_items["discount"],
    order_items["line_total"],
    alpha=0.3,
    color="#6366f1",
    s=15
)
ax.set_title("Discount vs Line Total — Does Discounting Drive Higher Spend?")
ax.set_xlabel("Discount Rate")
ax.set_ylabel("Line Total (€)")
ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{x*100:.0f}%"))
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"€{x:.0f}"))
plt.tight_layout()
plt.savefig("analysis/chart_discount_correlation.png", dpi=150, bbox_inches="tight")
plt.show()

"""Finding: discount level shows no correlation with higher line total.
Customers who spend €1500+ do so regardless of discount applied.
Recommendation: replace blanket discounts with targeted offers
for specific segments (e.g. reactivation campaigns for churned customers).
"""